# action.yml
name: "42Crunch REST API Static Security Testing"
description: "The REST API Static Security Testing action adds an automatic static application security testing (SAST) to your workflows"
inputs:
  upload-to-code-scanning:
    description: "Upload results to Code Scanning Alerts"
    required: false
    default: "true"
  enforce-sqg:
    description: "Enforce Security Quality Gate"
    required: false
    default: "false"
  log-level:
    description: "Log level"
    required: false
    default: "info"
  sarif-report:
    description: "SARIF report"
    required: false
  export-as-pdf:
    description: "Export as PDF"
    required: false
    default: "false"
  token:
    description: "Personal Access Token"
    default: ${{ github.token }}

branding:
  icon: "eye"
  color: "purple"
runs:
  using: "docker"
  image: "Dockerfile"

